config/routes.rb
Rails.application.routes.draw do
  resources :work_histories
  resources :education_histories
  resources :company_messages
  resources :job_seeker_messages
  resources :resumes
  resources :profiles
  devise_for :recruiters, controllers: { sessions: 'recruiters/sessions' } # TODO sessions以外も追加する
  devise_for :job_seekers, controllers: { sessions: 'job_seekers/sessions' } # TODO sessions以外も追加する
  root 'companies#index' # TODO ちゃんとする
  resources :job_offers
  resources :companies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :recruiter
  has_many :job_offer
  has_many :company_message
  has_many :job_seeker_message
end

app/models/company_message.rb
class CompanyMessage < Message
  belongs_to :company
  belongs_to :job_seeker
end

app/models/education_history.rb
class EducationHistory < ApplicationRecord
  belongs_to :profile
end

app/models/job_offer.rb
class JobOffer < ApplicationRecord
  belongs_to :company
end

app/models/job_seeker.rb
class JobSeeker < User
  has_one :profile, dependent: :destroy
  has_one :resume
  has_many :job_seeker_message
  has_many :company_message
end

app/models/job_seeker_message.rb
class JobSeekerMessage < Message
  belongs_to :job_seeker
  belongs_to :company
end

app/models/message.rb
class Message < ApplicationRecord
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :job_seeker
  has_many :education_history
  has_many :work_history
end

app/models/recruiter.rb
class Recruiter < User
  belongs_to :company
end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :job_seeker
end

app/models/user.rb
class User < ApplicationRecord
  self.abstract_class = true
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :validatable, :confirmable, :lockable, :timeoutable, :trackable
end

app/models/work_history.rb
class WorkHistory < ApplicationRecord
  belongs_to :profile
end

app/controllers/education_histories_controller.rb
class EducationHistoriesController < ApplicationController
  before_action :set_education_history, only: [:show, :edit, :update, :destroy]

  # GET /education_histories
  # GET /education_histories.json
  def index
    @education_histories = EducationHistory.all
  end

  # GET /education_histories/1
  # GET /education_histories/1.json
  def show
  end

  # GET /education_histories/new
  def new
    @education_history = EducationHistory.new
  end

  # GET /education_histories/1/edit
  def edit
  end

  # POST /education_histories
  # POST /education_histories.json
  def create
    @education_history = EducationHistory.new(education_history_params)

    respond_to do |format|
      if @education_history.save
        format.html { redirect_to @education_history, notice: 'Education history was successfully created.' }
        format.json { render :show, status: :created, location: @education_history }
      else
        format.html { render :new }
        format.json { render json: @education_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /education_histories/1
  # PATCH/PUT /education_histories/1.json
  def update
    respond_to do |format|
      if @education_history.update(education_history_params)
        format.html { redirect_to @education_history, notice: 'Education history was successfully updated.' }
        format.json { render :show, status: :ok, location: @education_history }
      else
        format.html { render :edit }
        format.json { render json: @education_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /education_histories/1
  # DELETE /education_histories/1.json
  def destroy
    @education_history.destroy
    respond_to do |format|
      format.html { redirect_to education_histories_url, notice: 'Education history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education_history
      @education_history = EducationHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_history_params
      params.require(:education_history).permit(:profile_id, :school_name, :entrance_date, :graduation_date, :status)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:job_seeker_id, :name, :sex, :birthday, :address, :note)
    end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]

  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(resume_params)

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1
  # PATCH/PUT /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url, notice: 'Resume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.require(:resume).permit(:job_seeker_id, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/education_histories_helper.rb
module EducationHistoriesHelper
end

app/helpers/job_offers_helper.rb
module JobOffersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/work_histories_helper.rb
module WorkHistoriesHelper
end

app/views/education_histories/_form.html.erb
<%= form_with(model: education_history, local: true) do |form| %>
  <% if education_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(education_history.errors.count, "error") %> prohibited this education_history from being saved:</h2>

      <ul>
      <% education_history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :profile_id %>
    <%= form.text_field :profile_id %>
  </div>

  <div class="field">
    <%= form.label :school_name %>
    <%= form.text_field :school_name %>
  </div>

  <div class="field">
    <%= form.label :entrance_date %>
    <%= form.date_select :entrance_date %>
  </div>

  <div class="field">
    <%= form.label :graduation_date %>
    <%= form.date_select :graduation_date %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/education_histories/edit.html.erb
<h1>Editing Education History</h1>

<%= render 'form', education_history: @education_history %>

<%= link_to 'Show', @education_history %> |
<%= link_to 'Back', education_histories_path %>

app/views/education_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Education Histories</h1>

<table>
  <thead>
    <tr>
      <th>Profile</th>
      <th>School name</th>
      <th>Entrance date</th>
      <th>Graduation date</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @education_histories.each do |education_history| %>
      <tr>
        <td><%= education_history.profile %></td>
        <td><%= education_history.school_name %></td>
        <td><%= education_history.entrance_date %></td>
        <td><%= education_history.graduation_date %></td>
        <td><%= education_history.status %></td>
        <td><%= link_to 'Show', education_history %></td>
        <td><%= link_to 'Edit', edit_education_history_path(education_history) %></td>
        <td><%= link_to 'Destroy', education_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Education History', new_education_history_path %>

app/views/education_histories/new.html.erb
<h1>New Education History</h1>

<%= render 'form', education_history: @education_history %>

<%= link_to 'Back', education_histories_path %>

app/views/education_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Profile:</strong>
  <%= @education_history.profile %>
</p>

<p>
  <strong>School name:</strong>
  <%= @education_history.school_name %>
</p>

<p>
  <strong>Entrance date:</strong>
  <%= @education_history.entrance_date %>
</p>

<p>
  <strong>Graduation date:</strong>
  <%= @education_history.graduation_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @education_history.status %>
</p>

<%= link_to 'Edit', edit_education_history_path(@education_history) %> |
<%= link_to 'Back', education_histories_path %>