config/routes.rb
Rails.application.routes.draw do
  resources :work_histories
  resources :education_histories
  resources :company_messages
  resources :job_seeker_messages
  resources :resumes
  resources :profiles
  devise_for :recruiters, controllers: { sessions: 'recruiters/sessions' } # TODO sessions以外も追加する
  devise_for :job_seekers, controllers: { sessions: 'job_seekers/sessions' } # TODO sessions以外も追加する
  root 'companies#index' # TODO ちゃんとする
  resources :job_offers
  resources :companies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :recruiter
  has_many :job_offer
  has_many :company_message
  has_many :job_seeker_message
end

app/models/company_message.rb
class CompanyMessage < Message
  belongs_to :company
  belongs_to :job_seeker
end

app/models/education_history.rb
class EducationHistory < ApplicationRecord
  belongs_to :profile
end

app/models/job_offer.rb
class JobOffer < ApplicationRecord
  belongs_to :company
end

app/models/job_seeker.rb
class JobSeeker < User
  has_one :profile, dependent: :destroy
  has_one :resume
  has_many :job_seeker_message
  has_many :company_message
end

app/models/job_seeker_message.rb
class JobSeekerMessage < Message
  belongs_to :job_seeker
  belongs_to :company
end

app/models/message.rb
class Message < ApplicationRecord
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :job_seeker
  has_many :education_history
  has_many :work_history
end

app/models/recruiter.rb
class Recruiter < User
  belongs_to :company
end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :job_seeker
end

app/models/user.rb
class User < ApplicationRecord
  self.abstract_class = true
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :validatable, :confirmable, :lockable, :timeoutable, :trackable
end

app/models/work_history.rb
class WorkHistory < ApplicationRecord
  belongs_to :profile
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:job_seeker_id, :name, :sex, :birthday, :address, :note)
    end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]

  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(resume_params)

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1
  # PATCH/PUT /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url, notice: 'Resume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.require(:resume).permit(:job_seeker_id, :note)
    end
end

app/controllers/work_histories_controller.rb
class WorkHistoriesController < ApplicationController
  before_action :set_work_history, only: [:show, :edit, :update, :destroy]

  # GET /work_histories
  # GET /work_histories.json
  def index
    @work_histories = WorkHistory.all
  end

  # GET /work_histories/1
  # GET /work_histories/1.json
  def show
  end

  # GET /work_histories/new
  def new
    @work_history = WorkHistory.new
  end

  # GET /work_histories/1/edit
  def edit
  end

  # POST /work_histories
  # POST /work_histories.json
  def create
    @work_history = WorkHistory.new(work_history_params)

    respond_to do |format|
      if @work_history.save
        format.html { redirect_to @work_history, notice: 'Work history was successfully created.' }
        format.json { render :show, status: :created, location: @work_history }
      else
        format.html { render :new }
        format.json { render json: @work_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_histories/1
  # PATCH/PUT /work_histories/1.json
  def update
    respond_to do |format|
      if @work_history.update(work_history_params)
        format.html { redirect_to @work_history, notice: 'Work history was successfully updated.' }
        format.json { render :show, status: :ok, location: @work_history }
      else
        format.html { render :edit }
        format.json { render json: @work_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_histories/1
  # DELETE /work_histories/1.json
  def destroy
    @work_history.destroy
    respond_to do |format|
      format.html { redirect_to work_histories_url, notice: 'Work history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_history
      @work_history = WorkHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_history_params
      params.require(:work_history).permit(:profile_id, :company_name, :join_date, :leave_date, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/company_messages_helper.rb
module CompanyMessagesHelper
end

app/helpers/job_offers_helper.rb
module JobOffersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/work_histories_helper.rb
module WorkHistoriesHelper
end

app/views/work_histories/_form.html.erb
<%= form_with(model: work_history, local: true) do |form| %>
  <% if work_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work_history.errors.count, "error") %> prohibited this work_history from being saved:</h2>

      <ul>
      <% work_history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :profile_id %>
    <%= form.text_field :profile_id %>
  </div>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name %>
  </div>

  <div class="field">
    <%= form.label :join_date %>
    <%= form.date_select :join_date %>
  </div>

  <div class="field">
    <%= form.label :leave_date %>
    <%= form.date_select :leave_date %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/work_histories/edit.html.erb
<h1>Editing Work History</h1>

<%= render 'form', work_history: @work_history %>

<%= link_to 'Show', @work_history %> |
<%= link_to 'Back', work_histories_path %>

app/views/work_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Work Histories</h1>

<table>
  <thead>
    <tr>
      <th>Profile</th>
      <th>Company name</th>
      <th>Join date</th>
      <th>Leave date</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @work_histories.each do |work_history| %>
      <tr>
        <td><%= work_history.profile %></td>
        <td><%= work_history.company_name %></td>
        <td><%= work_history.join_date %></td>
        <td><%= work_history.leave_date %></td>
        <td><%= work_history.status %></td>
        <td><%= link_to 'Show', work_history %></td>
        <td><%= link_to 'Edit', edit_work_history_path(work_history) %></td>
        <td><%= link_to 'Destroy', work_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work History', new_work_history_path %>

app/views/work_histories/new.html.erb
<h1>New Work History</h1>

<%= render 'form', work_history: @work_history %>

<%= link_to 'Back', work_histories_path %>

app/views/work_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Profile:</strong>
  <%= @work_history.profile %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @work_history.company_name %>
</p>

<p>
  <strong>Join date:</strong>
  <%= @work_history.join_date %>
</p>

<p>
  <strong>Leave date:</strong>
  <%= @work_history.leave_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @work_history.status %>
</p>

<%= link_to 'Edit', edit_work_history_path(@work_history) %> |
<%= link_to 'Back', work_histories_path %>