config/routes.rb
Rails.application.routes.draw do
  resources :work_histories
  resources :education_histories
  resources :company_messages
  resources :job_seeker_messages
  resources :resumes
  resources :profiles
  devise_for :recruiters, controllers: { sessions: 'recruiters/sessions' } # TODO sessions以外も追加する
  devise_for :job_seekers, controllers: { sessions: 'job_seekers/sessions' } # TODO sessions以外も追加する
  root 'companies#index' # TODO ちゃんとする
  resources :job_offers
  resources :companies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :recruiter
  has_many :job_offer
  has_many :company_message
  has_many :job_seeker_message
end

app/models/company_message.rb
class CompanyMessage < Message
  belongs_to :company
  belongs_to :job_seeker
end

app/models/education_history.rb
class EducationHistory < ApplicationRecord
  belongs_to :profile
end

app/models/job_offer.rb
class JobOffer < ApplicationRecord
  belongs_to :company
end

app/models/job_seeker.rb
class JobSeeker < User
  has_one :profile, dependent: :destroy
  has_one :resume
  has_many :job_seeker_message
  has_many :company_message
end

app/models/job_seeker_message.rb
class JobSeekerMessage < Message
  belongs_to :job_seeker
  belongs_to :company
end

app/models/message.rb
class Message < ApplicationRecord
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :job_seeker
  has_many :education_history
  has_many :work_history
end

app/models/recruiter.rb
class Recruiter < User
  belongs_to :company
end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :job_seeker
end

app/models/user.rb
class User < ApplicationRecord
  self.abstract_class = true
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :validatable, :confirmable, :lockable, :timeoutable, :trackable
end

app/models/work_history.rb
class WorkHistory < ApplicationRecord
  belongs_to :profile
end

app/controllers/job_offers_controller.rb
class JobOffersController < ApplicationController
  before_action :set_job_offer, only: [:show, :edit, :update, :destroy]

  # GET /job_offers
  # GET /job_offers.json
  def index
    @job_offers = JobOffer.all
  end

  # GET /job_offers/1
  # GET /job_offers/1.json
  def show
  end

  # GET /job_offers/new
  def new
    @job_offer = JobOffer.new
  end

  # GET /job_offers/1/edit
  def edit
  end

  # POST /job_offers
  # POST /job_offers.json
  def create
    @job_offer = JobOffer.new(job_offer_params)

    respond_to do |format|
      if @job_offer.save
        format.html { redirect_to @job_offer, notice: 'Job offer was successfully created.' }
        format.json { render :show, status: :created, location: @job_offer }
      else
        format.html { render :new }
        format.json { render json: @job_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_offers/1
  # PATCH/PUT /job_offers/1.json
  def update
    respond_to do |format|
      if @job_offer.update(job_offer_params)
        format.html { redirect_to @job_offer, notice: 'Job offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_offer }
      else
        format.html { render :edit }
        format.json { render json: @job_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_offers/1
  # DELETE /job_offers/1.json
  def destroy
    @job_offer.destroy
    respond_to do |format|
      format.html { redirect_to job_offers_url, notice: 'Job offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_offer
      @job_offer = JobOffer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_offer_params
      params.require(:job_offer).permit(:company_id, :title, :content, :status, :public_status)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:job_seeker_id, :name, :sex, :birthday, :address, :note)
    end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]

  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(resume_params)

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1
  # PATCH/PUT /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url, notice: 'Resume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.require(:resume).permit(:job_seeker_id, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/company_messages_helper.rb
module CompanyMessagesHelper
end

app/helpers/job_offers_helper.rb
module JobOffersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/work_histories_helper.rb
module WorkHistoriesHelper
end

app/views/job_offers/_form.html.erb
<%= form_with(model: job_offer, local: true) do |form| %>
  <% if job_offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job_offer.errors.count, "error") %> prohibited this job_offer from being saved:</h2>

      <ul>
      <% job_offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company_id %>
    <%= form.text_field :company_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :public_status %>
    <%= form.number_field :public_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/job_offers/edit.html.erb
<h1>Editing Job Offer</h1>

<%= render 'form', job_offer: @job_offer %>

<%= link_to 'Show', @job_offer %> |
<%= link_to 'Back', job_offers_path %>

app/views/job_offers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Job Offers</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Title</th>
      <th>Content</th>
      <th>Status</th>
      <th>Public status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_offers.each do |job_offer| %>
      <tr>
        <td><%= job_offer.company %></td>
        <td><%= job_offer.title %></td>
        <td><%= job_offer.content %></td>
        <td><%= job_offer.status %></td>
        <td><%= job_offer.public_status %></td>
        <td><%= link_to 'Show', job_offer %></td>
        <td><%= link_to 'Edit', edit_job_offer_path(job_offer) %></td>
        <td><%= link_to 'Destroy', job_offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job Offer', new_job_offer_path %>

app/views/job_offers/new.html.erb
<h1>New Job Offer</h1>

<%= render 'form', job_offer: @job_offer %>

<%= link_to 'Back', job_offers_path %>

app/views/job_offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @job_offer.company %>
</p>

<p>
  <strong>Title:</strong>
  <%= @job_offer.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @job_offer.content %>
</p>

<p>
  <strong>Status:</strong>
  <%= @job_offer.status %>
</p>

<p>
  <strong>Public status:</strong>
  <%= @job_offer.public_status %>
</p>

<%= link_to 'Edit', edit_job_offer_path(@job_offer) %> |
<%= link_to 'Back', job_offers_path %>